# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ab90142ff0628a9d034536afe5f61e2e353824e24c31b4f15c1c5381a27900289b8db66c885e099ebec36634817888603716fb0dede75a32ff544c5446e65d46

test:
  secret_key_base: d0a3c86e02f9b8e87274d63416a5e2c7a0d2ba45332915df5e0fb823aa48ca7499885b8faedf7499c99088f9c75e430656bfc80314b9cf751af7c053c15d2b21

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
